version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis-db
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data  # Using a named volume

volumes:
  redis_data:  # Define the named volume
